name: Deploy NestJS with Prisma and Redis to VPS using Docker Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy over SSH and run Docker Compose
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "Creating project folder if it doesn't exist!"

            if [ ! -d "web_bot_backend/.git" ]; then
              echo "Cloning repository!" 
              git clone https://github.com/tuxtasinboyev/web_bot_backend.git
            fi

            cd  web_bot_backend    # Shu yerda docker-compose.yml mavjud

            echo "Pulling latest changes!"
            git reset --hard
            git clean -fd
            git pull origin main  

            echo "Stopping containers"
            docker-compose down || true

            echo "Building containers"
            docker-compose build

            echo "Running containers"
            docker-compose up -d

            echo "✅ Deploy finished successfully!"



            
